
package AirlineSystem;
import javax.swing.JOptionPane;
/**
 *
 * @author Family
 */
public class SeatSelectionGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SeatSelectionGUI.class.getName());
    private Airline airline;
    private Flight flight;
    private Seat selectedSeat;
    private Booking booking;
    private BookingManager bookingManager;
    /**
     * Creates new form SeatSelectionGUI
     */
    public SeatSelectionGUI(Airline airline, Flight flight) {
        this.airline = airline;
        this.flight = flight;
        this.bookingManager = airline.getBookingManager();
        
        initComponents();
        setLocationRelativeTo(null);
        loadSeats();
    }

    private void loadSeats() {

    Aircraft aircraft = flight.getAircraft();

    String[] columns = {"Seat", "Status"};

    javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(columns, 0);

    for (Seat s : aircraft.getSeats()) {

        model.addRow(new Object[]{
            s.getSeatNumber(),
            s.isSeatAvailable() ? "AVAILABLE" : "TAKEN"
        });
    }

    tblSeats.setModel(model);
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSeats = new javax.swing.JTable();
        btnSelectSeat = new javax.swing.JButton();
        btnContinue = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblSeats.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblSeats);

        jScrollPane2.setViewportView(jScrollPane1);

        btnSelectSeat.setText("Select Seat");
        btnSelectSeat.addActionListener(this::btnSelectSeatActionPerformed);

        btnContinue.setText("Continue to Payment");
        btnContinue.addActionListener(this::btnContinueActionPerformed);

        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Select Your Seat");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(btnSelectSeat)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnContinue)
                .addGap(91, 91, 91))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(jLabel2)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(btnSelectSeat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnContinue)
                    .addComponent(btnBack))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectSeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectSeatActionPerformed
        // TODO add your handling code here:
        int row = tblSeats.getSelectedRow();

        if (row == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Select a seat from the table first.");
            return;
        }

        String seatNum = tblSeats.getValueAt(row, 0).toString();

        Seat seat = flight.getAircraft().findSeat(seatNum);

        if (seat == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seat not found.");
            return;
        }

        if (!seat.isSeatAvailable()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seat already taken.");
            return;
        }

        selectedSeat = seat;

        seat.setAvailability(false);
        loadSeats();
        
        // TEMP passenger (gets changed in PaymentGUI)
        Passenger tempPassenger = new Passenger("TEMP","TEMP","TEMP","TEMP");
        
        booking = bookingManager.createBooking(tempPassenger);
        
        booking.addTicket(new Ticket(
            "T" + System.currentTimeMillis(),
            flight,
            selectedSeat,
            "PENDING",
            tempPassenger
        ));

        JOptionPane.showMessageDialog(this,
            "Seat selected: " + seatNum +
            "\nBooking created: " + booking.getBookingID()
        );

    }//GEN-LAST:event_btnSelectSeatActionPerformed

    private void btnContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinueActionPerformed
        // TODO add your handling code here:
        if (selectedSeat == null || booking == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Select a seat first.");
            return;
        }

        new PaymentGUI(airline, flight, selectedSeat, booking).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnContinueActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        new FlightSelectionGUI(airline).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        System.out.println("Run in main.java please ");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnContinue;
    private javax.swing.JButton btnSelectSeat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblSeats;
    // End of variables declaration//GEN-END:variables
}
